Add modular scss
salielim/little-bluebird pull request #2
Opened 2017-01-12 23:49 UTC by salielim

2017-01-13 13:02 UTC, roberthopman reviewed
nice refactoring, 2 comments left 👍

2017-01-13 13:02 UTC, roberthopman commented on app/assets/stylesheets/components/_sidebar.scss
> +/* sidebar */
Can be removed.

2017-01-13 13:02 UTC, roberthopman commented on app/assets/stylesheets/custom.css.scss
> +@import "components/users_index";
What is the right order to load the base & components? cc @emile

2017-01-13 13:08 UTC, salielim commented on app/assets/stylesheets/custom.css.scss
> +@import "components/users_index";
i wonder about this too

2017-01-13 13:53 UTC, emilebosch requested changes
Fix this:
- modules
- components
- vars
- remove excessive imports

2017-01-13 13:53 UTC, emilebosch commented on app/assets/stylesheets/base/_fonts.scss
> +$gray-light: #D3D3D3;
put in `_vars`

2017-01-13 13:53 UTC, emilebosch commented on app/assets/stylesheets/base/_typography.scss
> +@import "fonts";
no need to import

2017-01-13 13:53 UTC, emilebosch commented on app/assets/stylesheets/components/_users_index.scss
> +.users {
modules/_user-list.scss

.mod-user-list {

}

2017-01-13 13:53 UTC, emilebosch commented on app/assets/stylesheets/custom.css.scss
> +@import "components/users_index";
```
@import "base/mixins";
 +@import "base/universal";
 +@import "base/typography";
 +@import "base/debug";
 +
 +@import "components/*";
 +@import "modules/*";

```

2017-01-14 14:02 UTC, roberthopman reviewed
just 1 comment

2017-01-14 14:02 UTC, roberthopman commented on app/assets/stylesheets/components/_footer.scss
> +@import "base/fonts";
do we need to import this, if it's already loaded? (base is before components) @emilebosch ?

2017-01-14 14:31 UTC, emilebosch commented on app/assets/stylesheets/components/_footer.scss
> +@import "base/fonts";
try to remove it and see what it does!

SPOILER: If its loaded no need to `@import` it again

2021-08-17 05:40 UTC, closed without merging